default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # TODO: configure match/certificates and app identifier
    capture_build_number
    build_app(scheme: "BitcoinBankApp")
    upload_to_testflight
  end

  desc "Release to App Store"
  lane :release do
    capture_build_number
    build_app(scheme: "BitcoinBankApp")
    upload_to_app_store
  end
end
